import numpy as np
print(np.binary_repr(40, width = 8))
print(np.binary_repr(np.left_shift(40,0)))
print(np.binary_repr(np.left_shift(40,1)))
print(np.binary_repr(np.left_shift(40,2)))
print(np.binary_repr(np.left_shift(40,3)))
print(np.binary_repr(np.left_shift(40,4)))
print(np.binary_repr(np.right_shift(40,0)))
print(np.binary_repr(np.right_shift(40,1)))
print(np.binary_repr(np.right_shift(40,2)))
print(np.binary_repr(np.right_shift(40,3)))
print(np.binary_repr(np.right_shift(40,4)))
print(np.binary_repr(np.right_shift(40,5)))
print(np.binary_repr(np.right_shift(40,6)))
print(np.binary_repr(np.right_shift(40,7)))